name: Build with CMake

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up CMake
        run: sudo apt-get update && sudo apt-get install -y cmake
      
      - name: Build
        run: cmake -S core -B build -DCMAKE_BUILD_TYPE=Release -DPROJECT_VERSION=${{ env.VERSION }}

      - name: Package
        run: |
          mkdir release
          ls build/out
          cp build/out/BinomialAmericanOption release/
          tar -czvf release_${{ github.ref_name }}.tar.gz -C release .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release_${{ github.ref_name }}.tar.gz
