name: Build Binaries

on:
  workflow_run:
    workflows: ["Bump New Release Version"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-linux-amd64:
    name: Build for linux/amd64 architecture
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configure CMake for linux-amd64
        id: configure_cmake
        run: cmake -S core -B build -DCMAKE_BUILD_TYPE=Release -DPROJECT_VERSION=${{ env.VERSION }}

      - name: Build
        id: build
        run: |
          mkdir release
          cd build
          make
          cd ..

      - name: Package Binary
        id: package_binary
        run: |
          cp build/out/BinomialAmericanOption release/
          tar -czvf binomial-american-option-v${{ env.VERSION }}-linux-x86_64.tar.gz -C release .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: binomial-american-option-v${{ env.VERSION }}-linux-x86_64.tar.gz

  build-linux-aarch64:
    name: Build Project for linux/aarch64 architecture
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: aarch64

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: Configure CMake for aarch64
        id: configure_cmake
        run: |
          mkdir -p build
          cmake -S core -B build -DCMAKE_TOOLCHAIN_FILE=${GITHUB_WORKSPACE}/core/aarch64-toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DPROJECT_VERSION=${{ env.VERSION }}

      - name: Build
        id: build
        run: |
          cd build
          make
          cd ..

      - name: Package
        id: package_binary
        run: |
          mkdir release
          cp build/out/BinomialAmericanOption release/
          tar -czvf binomial-american-option-v${{ env.VERSION }}-linux-aarch64.tar.gz -C release .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: binomial-american-option-v${{ env.VERSION }}-linux-aarch64.tar.gz
