name: Bump New Release Version

on:
  release:
    types: [created]

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update version file
        id: update_version_file
        run: |
          echo ${{ env.VERSION }} > core/VERSION
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add core/VERSION
          git commit -m "Bump core version to ${{ env.VERSION }}"

      - name: Push changes
        run: git push origin HEAD:main
